---
theme:
  color: green
  style: classic
  font_size: 10

personal_data:
  name:
    first: Michael
    last: Haynes
  desired_title: Data Engineer
  address:
    street: 5 Mill Road
    city: Hopkins
    state: MN
    zip: 55305
  mobile: (952)426-8758
  email: antihaynes@gmail.com
  extrainfo:
    - www.linkedin.com/in/antihaynes
    - https://github.com/antimike

experience:
  software:
    - start: May 2023
      end: Present
      title: Software Developer
      company: Open Access Technology International (OATI)
      location: Bloomington, MN
      brief_description: Full-stack enterprise software development.
      line_items:
        - Current Project: Time-series forecasting and machine-learning SaaS Web application
        - Requested by project leader as a team resource due to Python, Web development, and CI/CD expertise after providing mentorship and assistance in math methods, signal processing, and Python best practices to team member
        - \emph{Backend:} Python 3.8 implementations of ML-based timeseries forecasting algorithms using Keras, TensorFlow, and Scikit-Learn
        - - \emph{API:} ASP.NET Core with Entity Framework
          - \emph{Persistence:} MongoDB, PostgreSQL
        - - \emph{DevOps:} Gitlab, Ansible, Rundeck
          - \emph{Message queue:} Kafka
        - Responsibilities: ""
        - Modernizing and refactoring an extensive Python 3.8 backend
        - Driving the implementation of CI/CD and development best practices through an Agile methodology
        - Integrating performance-testing and benchmarking methods into our review and deployment process
        - Previous Project: Embedded microgrid control system
        - - \emph{Application:} Java SpringBoot
          - \emph{Persistence:} MongoDB, PostgreSQL, SQL Server
        - - \emph{UI:} Enterprise framework based on Ext.JS
          - \emph{DevOps:} Jenkins, Pacemaker, Ansible
    - start: March 2018
      end: September 2019
      title: Associate Consultant
      company: Magenic Technologies
      location: St. Louis Park, MN
      brief_description: Full-stack Web development focused on ASP.NET, SQL Server, and Angular.
      line_items:
        - Project: Cloud-based client onboarding webapp and dashboard built with .NET Core, Entity Framework, SQL Server, Angular 6, and Azure DevOps.
        - Built a provisioning pipeline for cloud-based client resources using Azure DevOps
        - Spearheaded effort to implement role-based user authentication
        - Delivered significant work across the full tech stack, including database migrations and stored procedures, .NET microservices, and UI feature development
    - start: 2012
      end: 2019
      title: Private Tutor
      company: Ferguson Tutoring
      location: Minnetonka, MN
      brief_description: Science and mathematics tutor specializing in one-on-one sessions with university and advanced high school students.
      line_items:
        - Subjects: Math, computer science, and physics (all levels); biology and chemistry (through university freshman level)

education:
  - title: Graduate Student, Physics
    start: September 2019
    end: May 2021
    institution: Colorado State University
    location: Fort Collins, CO
    brief_description: Completed coursework and conducted research in solid-state physics.
    line_items:
      - Research: Computational work focusing on Ginzburg-Landau theory using finite-element libraries in Python and C++
      - Teaching: TA, grading, and tutoring work for undergraduate classes in mechanics, thermodynamics, and labs
  - title: B.S. in Physics, concentration in Theory
    start: September 2009
    end: June 2016
    institution: Stanford University
    location: Stanford, CA
    brief_description: ""
    line_items:
      - Coursework: Datastructures and algorithms (C/C++); numerical work in Matlab, Python, R, and Mathematica for physics labs; extensive math background, including analysis, differential equations, differential geometry, and topology
      - Theory: analysis, differential equations, mechanics, abstract algebra, field theory, representation theory, differential geometry, particle physics
      - Honors: William Lowell Putnam Mathematical Competition Top 100, 2010

technical_skills:
  categories:
    Languages:
      - C\#
      - Python
      - C/C++
      - Java
      - SQL
    UI:
      - React
      - Angular
      - Javascript/Typescript
      - Ext.JS
    Persistence:
      - PostgreSQL
      - SQL Server
      - MongoDB
      - Kafka
    Scientific:
      - numpy
      - scipy
      - SageMath
      - deal.II (FEM library)
    Scripting:
      - Bash
      - zsh
      - Lua
      - Perl
    Server:
      - ASP.NET Core
      - Spring
      - Node.JS
    Misc.:
      - Jira
      - Confluence
      - Swagger
      - GitLab
      - TFS
  line_items:
    - extensive Linux experience (Bash scripting, cron jobs, etc.)
